x-restart-policy: &restart_policy
  restart: unless-stopped

# version 3.4 or higher is required for referencing in yml
version: '3.4'

services:
  ###
  ### monitoring
  ###
  node-exporter:
    image: quay.io/prometheus/node-exporter  # :9100
    <<: *restart_policy
    # privileged: true
    # network_mode: host
    # pid: host
    volumes:
      # - '/:/host:ro,rslave'
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)'

  nginx-exporter:  # :9113
    image: nginx/nginx-prometheus-exporter
    <<: *restart_policy
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    depends_on:
      - nginx

  process-exporter:
    image: ncabatoff/process-exporter  # :9526
    <<: *restart_policy
    privileged: true
    volumes:
      - /proc:/host/proc
      - ./ps.yml:/config/config.yml
    command:
      - '-procfs'
      - '/host/proc'
      - '-config.path'
      - '/config/config.yml'

  prometheus:
    image: prom/prometheus  # :9090
    <<: *restart_policy
    # err="open /prometheus/queries.active: permission denied" #5976
    # https://github.com/prometheus/prometheus/issues/5976#issuecomment-540457847
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      # Allow relative URL in web.external-url #1583
      # https://github.com/prometheus/prometheus/issues/1583#issuecomment-395617142
      - '--web.external-url=http://dummy/prometheus'
      - '--web.route-prefix=/prometheus'
    # From inside of a Docker container, how do I connect to the localhost of the machine?
    # https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana  # :3000
    <<: *restart_policy
    # user: "472"
    user: root
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env.docker
    depends_on:
      - prometheus

  ###
  ### business
  ###
  filebrowser:
    image: filebrowser/filebrowser  # :80
    <<: *restart_policy
    volumes:
      - ./filebrowser/database:/database
      - ./filebrowser/settings.json:/.filebrowser.json
      - ./drive:/srv
    env_file:
      - .env.docker

  ###
  ### gateway + static file server
  ###
  nginx:
    image: nginx
    <<: *restart_policy
    ports:
      - "80:80"
    volumes:
      - ./nginx.basic.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/log:/var/log/nginx:rw
      - ./blog:/usr/share/nginx/html:ro
    env_file:
      - .env.docker

volumes:
  prometheus_data: {}
  grafana_data: {}
